development:
  adapter: mysql2
  database: db_development
  user: root
  pool: 5
  password: ##
  timeout: 5000

test:
  adapter: mysql2
  database: db_test
  user: root
  pool: 5
  password: #
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>