development:
  adapter: mysql2
  database: db_development
  user: root
  pool: 5
  password: ##
  timeout: 5000

test:
  adapter: mysql2
  database: db_test
  user: root
  pool: 5
  password: #
  timeout: 5000

production:
  adapter: mysql2
  database: db_production
  username: root
  pool: 5
  password: ##
  timeout: 5000